import { vazir } from "@/shared/components/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={vazir.className}>
      <body>{children}</body>
    </html>
  );
}

