import { vazir } from "@/shared/components/fonts/fonts";
import "./globals.css";
import LoaderWrapper from "@/shared/provider/LoaderWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={vazir.className}>
      <body className="min-h-screen">
        <LoaderWrapper>{children}</LoaderWrapper>
      </body>
    </html>
  );
}
