import { vazir } from "@/shared/components/fonts/fonts";
import "./globals.css";
import FooterWrapper from "@/shared/provider/FooterWrapper";
import Footer from "@/shared/components/layout/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={vazir.className}>
      <body>
        <FooterWrapper>{children}</FooterWrapper>
        <Footer />
      </body>
    </html>
  );
}
