const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
const VERSION = process.env.NEXT_PUBLIC_API_VERSION;

const API_CORE_URL = `${BASE_URL}${VERSION}/${process.env.NEXT_PUBLIC_API_CORE}/`;
const API_PACKAGE_URL = `${BASE_URL}${VERSION}/${process.env.NEXT_PUBLIC_API_PACKAGE}/`;
const API_TEXTBOOK_URL = `${BASE_URL}${VERSION}/${process.env.NEXT_PUBLIC_API_TEXTBOOK}/`;
const API_PAYMENT_URL = `${BASE_URL}${VERSION}/${process.env.NEXT_PUBLIC_API_PAYMENT}/`;
const API_EXAM_URL = `${BASE_URL}${VERSION}/${process.env.NEXT_PUBLIC_API_EXAM}/`;

export {
  BASE_URL,
  API_CORE_URL,
  API_PACKAGE_URL,
  API_TEXTBOOK_URL,
  API_PAYMENT_URL,
  API_EXAM_URL,
};
